image: gitpod/workspace-full-vnc:2022-03-10-03-45-16
ports:
  - port: 6080
    onOpen: open-preview
tasks:
  - name: set JAVA_TOOL_OPTIONS
    command: |
      echo export JAVA_TOOL_OPTIONS=\"$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false\" >> /home/gitpod/.bashrc
      source /home/gitpod/.bashrc
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
