image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
tasks:
  - name: set JAVA_HOME
    command: |
     rm /home/gitpod/.sdkman/candidates/java/current
     ln -s /home/gitpod/.sdkman/candidates/java/17.0.4.fx-zulu /home/gitpod/.sdkman/candidates/java/current
  - name: set JAVA_TOOL_OPTIONS
    command: |
      echo export JAVA_TOOL_OPTIONS=\"$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false\" >> /home/gitpod/.bashrc
      source /home/gitpod/.bashrc
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - github.vscode-pull-request-github
