name: Create and publish a package

on:
  push:
    branches: [ release ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Package with Maven
      env:
        TZ: 'Asia/Tokyo'
      run: mvn -B package --file pom.xml
    - name: Create Tag
      run: |
           echo "TAG_NAME=v$(TZ=Asia/Tokyo date +%Y%m%d)" >> $GITHUB_ENV
           git tag ${{ env.TAG_NAME }}
           git push origin ${{ env.TAG_NAME }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
    - name: Upload Release Jar Action
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/sqlv-0.0.1-SNAPSHOT.jar
        asset_name: sqlv.jar
        asset_content_type: application/java-archive
    - name: Upload Release Jar With Dependencies Action
      id: upload-release-asset-with-dependencies
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/sqlv-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        asset_name: sqlv-jar-with-dependencies.jar
        asset_content_type: application/java-archive
    - name: Upload jacoco result
      uses: actions/upload-artifact@v3
      with:
        name: jacoco
        path: target/site/jacoco
        retention-days: 30
